(set-register ?d '(file . "~/GitHub/Journal/dagbok.org"))
(set-register ?g '(file . "~/GitHub/"))
(set-register ?k '(file . "~/GitHub/emacs-config/README.org"))
(set-register ?l '(file . "~/GitHub/Notater/journaler/liq.org"))
(set-register ?s '(file . "~/GitHub/Notater/journaler/språk.org"))
(set-register ?R '(file . "~/home/bw/GitHub/Notater/org-roam/20220228125418-refinery.org"))
(set-register ?w '(file . "~/GitHub/Notater/møter/wmm.org"))
(set-register ?r '(file . "~/GitHub/Notater/org-roam/20220916064720-rapplenker.org"))
;; (set-register ?R '(file . "~/GitHub/Notater/journaler/repetisjon_emner.org"))
(set-register ?e '(file . "~/.emacs"))
