;; (require 'org-fc-hydra)

(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("elt" . "src emacs-lisp :tangle"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("pyt" . "src python :tangle"))
(add-to-list 'org-structure-template-alist '("sr" . "src racket"))
(add-to-list 'org-structure-template-alist '("srt" . "src racket :tangle"))
(add-to-list 'org-structure-template-alist '("sq" . "src sqlite"))
