(setq org-todo-fast-todo-selection t
      org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "DATA(D)" "PRES(p)" "BAL(b)" "FIN(f)" "PRAK(P)" "|" "DONE(d)"))
      org-todo-keyword-faces (quote (("TODO" :foreground "red" :background "white")
				     ("FIN" :foreground "red" :background "white")
				     ("NEXT" :foreground "blue" :background "white")
				     ("PRAK" :foreground "blue" :background "white")
				     ("DATA" :foreground "light slate grey" :background "white" :weight "bold")
				     ("PRES" :foreground "dark turquoise" :background "white" :weight "bold")
				     ("BAL" :foreground "dark olive green" :background "white" :weight "bold")
				     ("DONE" :foreground "dark green" :background "white" :weight "bold")
				     ("FERD" :foreground "dark green" :background "white" :weight "bold")
				     )))
