  (set-register ?c '(file . "~/.emacs.d/custom.el"))
  ;; (set-register ?c '(file . "~/notebook/col.org"))
  ;; (set-register ?d '(file . "~/.emacs.d/snippets/org-mode/dayrep"))
  ;; (set-register ?e '(file . "~/.emacs"))
  (set-register ?j '(file . "c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\journal.org"))
  (set-register ?f '(file . "c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\fundamentals.org"))
  (set-register ?l '(file . "c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\liq.org"))
  (set-register ?l '(file . "c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\reg.org"))
  (set-register ?v '(file . "c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\vedlikehold.org"))

  (set-register ?o '(file . "c:/users/bjorwa/appdata/roaming/notebook/oversikt.org"))
  (set-register ?m '(file . "c:/users/bjorwa/appdata/roaming/notebook/markedsvurdering.org"))
  (set-register ?p '(file . "c:/users/bjorwa/appdata/roaming/notebook/prices.org"))

  (set-register ?d '(file . "c:\\users\\bjorwa\\desktop\\"))
  (set-register ?g '(file . "c:\\users\\bjorwa\\documents\\GitHub\\"))

  ;; (set-register ?p '(file . "~/notebook/python.org"))
  ;; (set-register ?r '(file . "~/notebook/rapporter.org"))
  ;; (set-register ?r '(file . "~/.emacs.d/reg.el"))

    ;; (set-register ?c '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\emacs-config\\custom.el"))
    ;;   (set-register ?g '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\"))
    ;;   (set-register ?c '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\notater\\ferdigheter.org"))
    ;;   (set-register ?k '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\emacs-config\\readme.org"))
    ;;   (set-register ?i '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\notater\\informatikk.org"))
    ;;   (set-register ?j '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\informatikk.org"))
    ;;   (set-register ?l '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\liq.org"))
    ;;   (set-register ?r '(file . "~c:\\users\\bjorwa\\documents\\GitHub\\markedsanalyse\\journaler\\reg.org"))
    ;;   (set-register ?e '(file . "~c:\\users\\bjorwa\\appdata\\roaming\\.emacs"))
