(set-register ?c '(file . "~/.emacs.d/custom.el"))
;; (set-register ?C '(file . "~/notebook/col.org"))
;; (set-register ?d '(file . "~/.emacs.d/snippets/org-mode/dayrep"))
;; (set-register ?e '(file . "~/.emacs"))
(set-register ?j '(file . "C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\journal.org"))
(set-register ?f '(file . "C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\fundamentals.org"))
(set-register ?L '(file . "C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\liq.org"))
(set-register ?l '(file . "C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\reg.org"))
(set-register ?v '(file . "C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\vedlikehold.org"))

(set-register ?o '(file . "C:/Users/bjorwa/AppData/Roaming/notebook/oversikt.org"))
(set-register ?m '(file . "C:/Users/bjorwa/AppData/Roaming/notebook/markedsvurdering.org"))
(set-register ?p '(file . "C:/Users/bjorwa/AppData/Roaming/notebook/prices.org"))

(set-register ?d '(file . "C:\\Users\\bjorwa\\Desktop\\"))
(set-register ?g '(file . "C:\\Users\\bjorwa\\Documents\\GitHub\\"))

;; (set-register ?P '(file . "~/notebook/python.org"))
;; (set-register ?r '(file . "~/notebook/rapporter.org"))
;; (set-register ?R '(file . "~/.emacs.d/reg.el"))

  ;; (set-register ?c '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\emacs-config\\custom.el"))
  ;;   (set-register ?g '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\"))
  ;;   (set-register ?c '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\Notater\\ferdigheter.org"))
  ;;   (set-register ?k '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\emacs-config\\README.org"))
  ;;   (set-register ?i '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\Notater\\informatikk.org"))
  ;;   (set-register ?j '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\informatikk.org"))
  ;;   (set-register ?l '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\liq.org"))
  ;;   (set-register ?r '(file . "~C:\\Users\\bjorwa\\Documents\\GitHub\\Markedsanalyse\\journaler\\reg.org"))
  ;;   (set-register ?e '(file . "~C:\\Users\\bjorwa\\AppData\\Roaming\\.emacs"))
